add event sources yaml
CJSCommonPlatform/generator-maven-plugin pull request #15
Opened 2018-04-09 13:43 UTC by MohamedFarouk-HMCTS

2018-04-09 13:49 UTC, MohamedFarouk-HMCTS commented on subscription-descriptor-parser/src/main/java/uk/gov/justice/maven/generator/io/files/parser/eventsource/EventSourcesFileParser.java
> +import uk.gov.justice.maven.generator.io.files.parser.subscriptiondescriptor.SubscriptionDescriptorException;
removed

2018-04-09 13:50 UTC, MohamedFarouk-HMCTS commented on subscription-descriptor-parser/src/main/java/uk/gov/justice/maven/generator/io/files/parser/subscriptiondescriptor/SubscriptionDescriptorFileParserFactory.java
> +import uk.gov.justice.maven.generator.io.files.parser.YamlFileValidator;
removed

2018-04-09 13:52 UTC, MohamedFarouk-HMCTS commented on subscription-descriptor-parser/src/main/java/uk/gov/justice/maven/generator/io/files/parser/subscriptiondescriptor/SubscriptionDescriptorFileParserFactory.java
> +    private static final String yamlSchemaFileName = "/json/schema/subscription-schema.json";
renamed

2018-04-09 13:53 UTC, MohamedFarouk-HMCTS commented on subscription-descriptor-parser/src/main/java/uk/gov/justice/maven/generator/io/files/parser/subscriptiondescriptor/SubscriptionDescriptorYamlFileValidator.java
> +import uk.gov.justice.maven.generator.io.files.parser.eventsource.EventSourcesException;
removed

2018-04-09 14:00 UTC, MohamedFarouk-HMCTS commented on subscription-descriptor-parser/src/main/java/uk/gov/justice/domain/eventsource/EventSources.java
> +    private final List<EventSource> eventSources;
suppressed warning as i need this to be called eventSources for jackson pojo mapping

2018-04-09 14:02 UTC, MohamedFarouk-HMCTS commented on subscription-descriptor-parser/src/main/java/uk/gov/justice/maven/generator/io/files/parser/eventsource/EventSourcesFileParserFactory.java
> +    private static final String yamlSchemaFileName = "/json/schema/event-source-schema.json";
Suppressed warning "squid:S1075" as I dont want to bring in from configuration file

2018-04-10 08:21 UTC, mapingo requested changes
The subscription yaml has been moved to the framework.  The event source changes should be applied to the framework.

2018-04-12 12:38 UTC, closed without merging